name: billiards

services:
  billiards-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: billiards-ui-dev
    ports:
      - "3009:3009"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3009
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3005/api/v1
      - HOST=0.0.0.0
    # env_file:
    #   - .env
