name: billiards

services:
  billiards-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev.reload
    container_name: billiards-ui-dev
    ports:
      - "3009:3009"
    volumes:
      - ./scripts:/app/scripts
      - ./src:/app/src
      - ./.browserslistrc:/app/.browserslistrc
      - ./.commitlintrc.js:/app/.commitlintrc.js
      - ./index.html:/app/index.html
      - ./jest.config.js:/app/jest.config.js
      - ./jest.setup.js:/app/jest.setup.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./vite.config.js:/app/vite.config.js
      - ./webpack.config.js:/app/webpack.config.js
    environment:
      - PORT=3009
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3005/api/v1
      - HOST=0.0.0.0
    # env_file:
    #   - .env
